# Generated by Django 5.2.14 on 2026-05-21 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='company',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='company',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='contractor',
        ),
        migrations.DeleteModel(
            name='WebhookEvent',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Payout',
        ),
    ]
